development:
  host: localhost
  port: 6379

staging:
  host: processor-adattributes-sandbox-001.tgdqqn.0001.use1.cache.amazonaws.com
  port: 6379

production:
  host: insert-prod-db-details
  port: 6369